[profile.default]
solc = "0.8.26"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin=lib/openzeppelin-contracts",
    "@openzeppelin=lib/@openzeppelin",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
